### ISSUE TITLE
Can't install this plugin

### ISSUE THREAD

**Issue by labs01** [dreampiggy/cocoapods-xcode-patch#2]
I got error when install using bundle

bundle install
> Fetching source index from https://rubygems.pkg.github.com/dreampiggy/
> 
> Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.pkg.github.com/dreampiggy/
> 
> Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.pkg.github.com/dreampiggy/
> 
> Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.pkg.github.com/dreampiggy/
> 
> Could not fetch specs from https://rubygems.pkg.github.com/dreampiggy

**Comment by dreampiggy** [comment]
@labs01 Seems GitHub Package RubyGem spec is not ready. At that time I test, it can download, but now it fails.

It's easy, just using the local gem file (download [here])https://github.com/dreampiggy/cocoapods-xcode-patch/packages/23260)), or use the git dependency instead:

```ruby
gem 'cocoapods-xcode-patch', :git => 'https://github.com/dreampiggy/cocoapods-xcode-patch.git'
```
